wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.34.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707050567.226842
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 79
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 79
      3:
      - 17
      - 23
      - 37
      4: 3.11.4
      5: 0.16.2
      6: 4.34.0
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
